name: Fly Deploy
on: [push]
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  deploy:
      name: Deploy app
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: superfly/flyctl-actions/setup-flyctl@master
        - name: create .env
          run: |
              touch .env
              echo SENTRY_DSN=${{ secrets.SENTRY_DSN }} >> .env
        - name: deploy
          run: flyctl deploy --remote-only