name: Deploy or Ignore
on:
  push:
    branches: ["main"]
jobs:
  build-or-ignore:
      name: Build only on changes
      runs-on: ubuntu-latest
      strategy:
        fail-fast: false
        matrix:
          package: ["kiosk-web"]
      steps:
        - name: Cancel Previous Runs
          uses: styfle/cancel-workflow-action@0.9.1
        - name: Check out code
          uses: actions/checkout@v3
        - name: Checking for changes
          run: npx turbo-ignore ${{ matrix.package }}
          env:
            TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
            TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
        - name: Build and Deploy
          if: ${{ failure() }}
          uses: ./.github/actions/build-or-ignore.yml
          with:
            package: ${{ matrix.package }}
            FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
            TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
            TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
            VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
            VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}