name: Build or Ignore
on:
  push:
    branches: ["main"]
jobs:
  build-or-ignore:
      name: Build and Deploy
      runs-on: ubuntu-latest
      strategy:
        fail-fast: false
        matrix:
          package: ["kiosk-web"]
      steps:
        - name: Cancel Previous Runs
          uses: styfle/cancel-workflow-action@0.9.1
        - name: Check out code
          uses: actions/checkout@v3
          with:
            fetch-depth: 0
        - name: Installing flyctl
          uses: superfly/flyctl-actions/setup-flyctl@master
        - name: Checking for changes
          run: |
            tag=$(flyctl image show  --config ./apps/${{ matrix.package }}/fly.toml -j | node -pe 'JSON.parse(fs.readFileSync(0)).Tag.split("-")[1]')
            npx turbo-ignore ${{ matrix.package }} --fallback=$tag
          env:
            VERCEL: 1
            FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
            TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
            TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
        - name: Build and Deploy
          if: ${{ failure() }}
          uses: ./.github/actions/deploy.yml
          with:
            package: ${{ matrix.package }}
            FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
            TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
            TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
            VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
            VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}