name: Deploy to Fly
on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
jobs:
  deploy:
      name: Deploy app
      strategy:
        matrix:
          package: ["kiosk-web", "client-web"]
      runs-on: ubuntu-latest
      steps:
        - name: Cancel Previous Runs
          uses: styfle/cancel-workflow-action@0.9.1
        - name: Check out code
          uses: actions/checkout@v3
        - name: Setup Node.js environment
          uses: actions/setup-node@v3
          with:
            node-version: 16
            cache: 'yarn'
        - name: Installing flyctl
          uses: superfly/flyctl-actions/setup-flyctl@master
        - name: Fetching environment variables
          run: vercel env pull --yes --token ${{ secrets.TURBO_TOKEN }}
        - name: Install dependencies
          run: yarn
        - name: Deploy
          run: yarn deploy --filter=${{ matrix.package }}...