name: Deploy to Fly
on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
jobs:
  deploy:
      name: Deploy app
      strategy:
        matrix:
          package: ["kiosk-web", "client-web"]
      runs-on: ubuntu-latest
      steps:
        - name: Cancel Previous Runs
          uses: styfle/cancel-workflow-action@0.9.1
        - name: Check out code
          uses: actions/checkout@v3
        - name: 👀 Read app name
          uses: SebRollen/toml-action@v1.0.2
          id: app_name
          with:
            file: apps/${{ matrix.package }}/fly.toml
            field: app
        - name: Fetching environment variables
          run: vercel env pull --yes --token ${{ secrets.TURBO_TOKEN }}
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2
          # Setup cache
        - name: Cache Docker layers
          uses: actions/cache@v3
          with:
            path: /tmp/.buildx-cache
            key: ${{ runner.os }}-buildx-${{ github.sha }}
            restore-keys: |
              ${{ runner.os }}-buildx-
        - name: Fly Registry Auth
          uses: docker/login-action@v2
          with:
            registry: registry.fly.io
            username: x
            password: ${{ secrets.FLY_API_TOKEN }}
        - name: 🐳 Docker build
          uses: docker/build-push-action@v3
          with:
            context: .
            file: apps/${{ matrix.package }}/Dockerfile
            push: true
            tags: registry.fly.io/${{ steps.app_name.outputs.value }}:${{ github.ref_name }}-${{ github.sha }}
            build-args: |
              COMMIT_SHA=${{ github.sha }}
            cache-from: type=gha
            cache-to: type=gha,mode=max
        - name: Installing flyctl
          uses: superfly/flyctl-actions/setup-flyctl@master
        - name: Deploy
          run: flyctl deploy --config ./apps/${{ matrix.package }}/fly.toml --image registry.fly.io/${{ steps.app_name.outputs.value }}:${{ github.ref_name }}-${{ github.sha }}
