name: Deploy to Fly
on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
jobs:
  deploy:
      name: Deploy app
      runs-on: ubuntu-latest
      steps:
        - name: Check out code
          uses: actions/checkout@v3
        - name: Setup Node.js environment
          uses: actions/setup-node@v3
          with:
            node-version: 16
            cache: 'yarn'
        - name: Installing flyctl
          uses: superfly/flyctl-actions/setup-flyctl@master
        - name: Installing Turborepo
          uses: yarn global add turbo
        - name: Setting up necessary environment variables.
          uses: echo 'SENTRY_DSN=${{ secrets.SENTRY_DSN }}' >> .env
        - name: Deploy
          uses: turbo run deploy